# File: EProject-Phase-1/docker-compose.yml
version: '3.8'

services:
  # Service MongoDB Database
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Service AUTH
  auth:
    build: ./auth
    container_name: auth-service
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mongo

  # Service PRODUCT
  product:
    build: ./product
    container_name: product-service
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    depends_on:
      - mongo

  # Service ORDER
  order:
    build: ./order
    container_name: order-service
    ports:
      - "3002:3002"
    env_file:
      - ./.env
    depends_on:
      - mongo

  # API GATEWAY
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8088:3003"
    env_file:
      - ./.env
    depends_on:
      - auth
      - product
      - order

volumes:
  mongo-data: